# Generated by Django 5.0.3 on 2024-04-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('estatura', models.DecimalField(max_digits=5, decimal_places=2)),
                ('peso', models.DecimalField(max_digits=5, decimal_places=2)),
            ],
        ),
    ]
