# Generated by Django 5.0.3 on 2024-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_persona_estatura_alter_persona_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='estatura',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='peso',
            field=models.TextField(),
        ),
    ]
